### ISSUE TITLE
Modelo de datos

### ISSUE THREAD

**Issue by mvcalderonc** [udistrital/produccion_academica_cliente#1]
Generar el modelo de datos para el sistema de producción académica

**Comment by mvcalderonc** [comment]
# Diseño modelo de datos
A continuación se encuentra el modelo de datos propuesto para el sistema de producción acádemica de la oficina de docencia v1

![new_database](https://user-images.githubusercontent.com/44048060/96940326-0f0b1800-1495-11eb-98cc-4a89f14786f2.png)

**Comment by mvcalderonc** [comment]
# Modelo de base de datos 
Se realizan ajustes al modelo de datos inicial, con lo cual queda así:
![Modelo de Base de Datos v3](https://user-images.githubusercontent.com/44048060/98184344-2d7f0380-1ed8-11eb-99ea-2cad4909d95c.png)

**Comment by fabianbarreto02** [comment]
Relacionar nuevas issue

**Comment by CrissUD** [comment]
Este Issue tiene una continuación a partir de los issues #16  y #19 @fabianbarreto02

**Comment by mvcalderonc** [comment]
ajustes a realizar al esquema de solicitud
	agregar notas en los campos que referencian otros sistemas
	tabla soporte_solicitud
		ajustar el campo documento a documento_id
	agregar tabla 
		paso de estados y persona que genera el cambio

**Comment by mvcalderonc** [comment]
# Modelo solicitud

![modelo_solicitud](https://user-images.githubusercontent.com/44048060/98880004-c374da00-2454-11eb-9b75-76912beaef19.png)

@fabianbarreto02

**Comment by mvcalderonc** [comment]
Nuevos ajustes:

en la tabla solicitud
- agregar fecha_radicacion
- modificar solicitud_id -> solicitud_padre_id

en la tabla solicitud_evolucion_estado
- agregar fecha_limite

en la tabla estado_tipo_solicitud
- agregar numero_dias
- agregar dependencia_id

**Comment by mvcalderonc** [comment]
@fabianbarreto02  se realizaron los ajustes indicados

![modelo_solicitud](https://user-images.githubusercontent.com/44048060/99011312-d3a2bd00-2519-11eb-90cb-3dbc4004db3b.png)

**Comment by fabianbarreto02** [comment]
Se realiza revisión de modelo en reunión junto a @corio27 @danzola @blacburn y se da aprobación del modelo, se da por finalizada la issue
