### ISSUE TITLE
Creación mockups fase 3

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#14]

**Comment by EstefaniaPerezTorres** [comment]
### Mockup de la fase 3
_Página para generar el documento de los según las solicitudes (filas) seleccionadas en el checkbox correspondiente._

![image](https://user-images.githubusercontent.com/72519041/97641813-c661da80-1a11-11eb-882d-6437450da54d.png)

_Página donde se muestran todos los documentos que existen. El botón "ver" descarga el documento y el de "detalles" abrirá una nueva página para ver las solicitudes que lo conforman_

![image](https://user-images.githubusercontent.com/72519041/97641936-0e80fd00-1a12-11eb-9043-52a24c6446a9.png)

_Al dar click en "Detalles" se dirige a está página donde se muestran las solicitudes que contiene el documento. Cada solicitud tiene la opción para "excluir" del documento, para comentar y para ver._

![image](https://user-images.githubusercontent.com/72519041/97642188-8c450880-1a12-11eb-86d7-6b6e221f6a63.png)

![image](https://user-images.githubusercontent.com/72519041/97642292-cadac300-1a12-11eb-8500-93425321ad71.png)

**Comment by fabianbarreto02** [comment]
Se realiza la revisión de la de los mockups, se da por finalizada la issue se autoriza en la [reunión](https://drive.google.com/file/d/1WsayeR_Q3OfOGeIgaQjmss4WBxS8POsa/view) con el usuario
