### ISSUE TITLE
Modelo relacional de base de datos para SOLICITUDES

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#16]

**Comment by mvcalderonc** [comment]
# Modelo de datos
A continuación se muestra el modelo de datos dividido en múltiples esquemas de manera que no quede ligado a las solicitudes de docencia
![modelo_solicitudes](https://user-images.githubusercontent.com/44048060/98319512-e9126700-1fae-11eb-9b8b-484190d43133.png)

**Comment by mvcalderonc** [comment]
Se deben realizar los siguientes ajustes a las tablas de los esquemas de solicitud y evaluacion_par_academico

- Eliminar la tabla evaluacion_par_academico.soporte_evaluacion
- Modificar campos referencia y resultado a json de las tablas solicitud.solicitud y evaluacion_par_academico.evaluacion
- Agregar campo valor de tipo json a la tabla evaluacion_par_academico.respuesta_item_evaluacion
- Agregar tabla de solicitud.solicitantes
- Agregar tabla de evaluacion_par_academico.evaluadores
- Agregar campos de lineamientos en tablas parametricas
- Ajustar campos de tipo bit por boolean
- Ajustar tipo de campo para identificador de tabla

**Comment by mvcalderonc** [comment]
# Ajuste de los esquemas de solicitud y evaluación

Se realizan los ajustes indicados en el comentario anterior en los esquemas de solicitud y evaluación, @fabianbarreto02 

![modelo_evaluacion](https://user-images.githubusercontent.com/44048060/98612368-06527880-22c2-11eb-9857-9b3784d160e0.png)
![modelo_solicitud](https://user-images.githubusercontent.com/44048060/98612369-08b4d280-22c2-11eb-9c25-4a951aeb8a08.png)

**Comment by fabianbarreto02** [comment]
Se da por revisado, los ajustes solicitados, se da por finalizada la issue
