### ISSUE TITLE
Diagrama de estados

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#17]

**Comment by EstefaniaPerezTorres** [comment]
### Diagrama de estados V1
![image](https://user-images.githubusercontent.com/72519041/98370867-43401600-2009-11eb-8061-bbf79923f5c1.png)

**Comment by fabianbarreto02** [comment]
Cambiar nombre estado evaluación por verificación @EstefaniaPerezTorres

**Comment by EstefaniaPerezTorres** [comment]
Se hace corrección del diagrama @fabianbarreto02
 [Documento en DRIVE](https://drive.google.com/file/d/1BljgABOI1NiegepdzxLHsSVWzqx013ab/view?usp=sharing)
![image](https://user-images.githubusercontent.com/72519041/98399203-0dfaee80-2030-11eb-97cc-8ce0292e95ff.png)

**Comment by fabianbarreto02** [comment]
Se revisa los ajustes, se da por finalizada la issue
