### ISSUE TITLE
Listado de tipos de solicitudes con sus respectivos subtipos y campos

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#18]

**Comment by CrissUD** [comment]
# Inserciones en la base de datos de producción Académica

Se realiza un análisis para insertar nuevos datos a la base de datos de **Producción académica** para lo cual se crea una inserción de:
* Tipos de producción. 
* Subtipos de producción.
* Tipos de metadatos.
* Metadato - Subtipo de producción.

A continuación se muestran los enlaces para observar dichas inserciones 
* Archivo Excel con todos los datos a insertar 
[Archivo Excel](https://docs.google.com/spreadsheets/d/1Ts3G6Q3DDV2P5cWz2X0zzWESF_F8JdndDrqjJkdBZ6E/edit?usp=sharing)
* Imagen con referencia de cada campo por cada subtipo de producción académica

<div align='center'>
    <img  src='https://i.imgur.com/6hicBox.jpg'>
    <p>Modulo de solicitud docente</p>
</div>

**Comment by fabianbarreto02** [comment]
Realizar ajustes de id

**Comment by CrissUD** [comment]
# Ajustes de ID

Se realizan los respectivos ajustes de ID en documento para que empiecen desde 1 en adelante:

A continuación se muestran los enlaces para observar dichas correcciones 
* Archivo Excel con todos los datos a insertar 
[Archivo Excel](https://docs.google.com/spreadsheets/d/1Ts3G6Q3DDV2P5cWz2X0zzWESF_F8JdndDrqjJkdBZ6E/edit?usp=sharing)

@fabianbarreto02

**Comment by fabianbarreto02** [comment]
Se revisa los ajustes realizados en el orden de los id, se da por finalizada la issue
