### ISSUE TITLE
Revisión modelo de la base de datos de producción académica

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#19]

**Comment by Camiloqui** [comment]
> 
![Modelo produccion academica](https://user-images.githubusercontent.com/19983790/98619782-ecb92d00-22d1-11eb-83eb-4009fd02d02c.png)

https://drive.google.com/file/d/1J923w_H6h4zcp9u_YAJjMaCBka2gYaj3/view?usp=sharing

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue

**Comment by Camiloqui** [comment]
![modelo_produccion_academica](https://user-images.githubusercontent.com/19983790/98688653-135e7e80-2339-11eb-990a-bdce4c8efe53.png)

**Comment by Camiloqui** [comment]
link de donde se encuentra ubicacion el archivo
https://drive.google.com/file/d/1x9TlbTsVan7f-U5y5RSSNR_d9mF78-ng/view?usp=sharing

**Comment by Camiloqui** [comment]
![produccion_academica](https://user-images.githubusercontent.com/19983790/98749742-4846f180-238a-11eb-9fd0-da0bfce38bb5.png)
https://drive.google.com/file/d/1w2wzeBv5H5mxZWlaPL61HoJpHt98dWbu/view?usp=sharing

**Comment by Camiloqui** [comment]
![modelo_produccion_academica](https://user-images.githubusercontent.com/19983790/98975460-22356480-24e4-11eb-8484-5d2e094ef784.png)
https://drive.google.com/file/d/1igLGJfcG3-QPN8EuHYGKzZEEMq1f-AJj/view?usp=sharing
