### ISSUE TITLE
Revisión post producción académica

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#20]

**Comment by CrissUD** [comment]
# Primera revisión de Post de produccion_academica_mid

## Comentarios 

A continuación se da una serie de comentarios sobre el proceso de POST para una producción académica

* Comentario 1
![comentario 1](https://user-images.githubusercontent.com/44172561/98834581-5ee25c80-240d-11eb-8f54-c6e9af956093.png)
* Comentario 2
![comentario 2](https://user-images.githubusercontent.com/44172561/98834622-6ace1e80-240d-11eb-88ae-635fd2f57c56.png)
* Comentario 3
![comentario 3](https://user-images.githubusercontent.com/44172561/98834702-80434880-240d-11eb-97cc-42f421f47bc0.png)
*Comentario 4 
![comentario 4](https://user-images.githubusercontent.com/44172561/98835988-217ece80-240f-11eb-9375-b544ca839e16.png)
* Comentario 5 
![comentario 6](https://user-images.githubusercontent.com/44172561/98834756-92bd8200-240d-11eb-9fa4-f899920a5a20.png)
* Comentario 6
![comentario 7](https://user-images.githubusercontent.com/44172561/98834867-b4b70480-240d-11eb-8ada-c6d41a50a127.png)

## Dudas

A continuación se da una serie de dudas sobre el proceso de POST para una producción académica
* Duda 1 
![comentario 5](https://user-images.githubusercontent.com/44172561/98835058-f3e55580-240d-11eb-952c-845529a8a6ea.png)
* Duda 2
![comentario 8](https://user-images.githubusercontent.com/44172561/98835089-fc3d9080-240d-11eb-9625-455f1df0e188.png)
* Duda 3
![comentario 9](https://user-images.githubusercontent.com/44172561/98836020-2d6a9080-240f-11eb-9970-57da511fecf0.png)

**Comment by CrissUD** [comment]
# Primera revisión Post de producción académica CRUD

## Comentarios
A continuación se da una serie de comentarios sobre el proceso de POST para una producción académica

### Controlador

* Comentario 1 
![Comentario 1](https://user-images.githubusercontent.com/44172561/98845928-5fceba80-241c-11eb-9ece-c209133dece1.png)
* Comentario 2
![Comentario 2](https://user-images.githubusercontent.com/44172561/98845954-6826f580-241c-11eb-908b-bccae2e6f39e.png)
* Comentario 3 
![Comentario 3](https://user-images.githubusercontent.com/44172561/98845975-7117c700-241c-11eb-870c-c2364dce323c.png)

### Modelo
* Comentario 1 
![Comentario 4](https://user-images.githubusercontent.com/44172561/98846023-8260d380-241c-11eb-9955-99f30fac7e41.png)
* Comentario 2 
![Comentario 5](https://user-images.githubusercontent.com/44172561/98846040-87be1e00-241c-11eb-9779-acc731e38259.png)
* Comentario 3 
![Comentario 6](https://user-images.githubusercontent.com/44172561/98846059-90165900-241c-11eb-8847-e50db0d545c6.png)
* Comentario 4 
![Comentario 7](https://user-images.githubusercontent.com/44172561/98846072-96a4d080-241c-11eb-950a-aec7dd257004.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
