### ISSUE TITLE
Cliente producción académica

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#21]

**Comment by CrissUD** [comment]
# Limpieza de proyecto y refactorización 

Se realiza la estructura del cliente para el proyecto de solicitudes de producción académica docencia, basándose del cliente **sga_cliente**, luego se realiza una limpieza del proyecto, específicamente en partes del proyecto como:
* Componentes dentro de **pages**.
* Servicios y modelos dentro de **data**.
* Archivos de traducción en **assets**.
* Archivos que contienen variables de entorno en **enviroment**.

Para revisar toda la refactorización del proyecto puede entrar al siguiente [pull request](https://github.com/udistrital/produccion_academica_cliente/pull/23).

**Comment by CrissUD** [comment]
# Ajustes de formularios de solicitudes de docencia

Se realiza toda una serie de ajustes para cada una de las solicitudes de producción académica docencia. 
Basándose en los [mockups para la solicitud de docentes](https://drive.google.com/file/d/1MysdxAlKGvvI_j1-9S9nELLsH2-5O7O5/view?usp=sharing) se realizaron unos ajustes en el formulario de producción académica acorde a las necesidades planteadas por la oficina de docencia, se crearon ajustes además en los formularios dinámicos para soportar varios ajustes adicionales. 

Se logro replicar la parte visual que los mockups reflejan y se espera una próxima revisión de envió de información a las respectivas apis para probar el envío de solicitudes por parte del docente. 

Para ver a detalle la trazabilidad de estos ajustes puede revisar los cambios [en el siguiente link](https://github.com/udistrital/produccion_academica_cliente/tree/feature/formProduccion)

**Comment by CrissUD** [comment]
# Evidencias de proceso 

A continuación se muestran algunos de los formularios desarrollados como muestra del proceso de codificación de mockups 

* Formulario de solicitud para un **Articulo Completo** 
![screencapture-localhost-4200-2020-11-17-21_56_01](https://user-images.githubusercontent.com/44172561/99477854-6203ae00-2921-11eb-87c2-07d6d1191ef2.png)

* Formulario de solicitud para un **Video, Cinematográfica o Fonografía** 
![screencapture-localhost-4200-2020-11-17-21_56_32](https://user-images.githubusercontent.com/44172561/99478020-ac852a80-2921-11eb-8426-61d43de5a5c4.png)

* Formulario de solicitud para un **Libro de investigación** 
![screencapture-localhost-4200-2020-11-17-21_56_55](https://user-images.githubusercontent.com/44172561/99478085-c58ddb80-2921-11eb-92b7-46f5e9d5bf8b.png)

* Formulario de solicitud para un **Estudio de postdoctorado** 
![screencapture-localhost-4200-2020-11-17-21_58_24](https://user-images.githubusercontent.com/44172561/99478158-e3f3d700-2921-11eb-87ed-cb2b3820d602.png)

* Formulario de solicitud para un **Capitulo de libro de investigación** 
![screencapture-localhost-4200-2020-11-17-21_57_41](https://user-images.githubusercontent.com/44172561/99478205-f706a700-2921-11eb-9941-3d0f95871e78.png)

**Comment by CrissUD** [comment]
# Correcciones para envío de peticiones de producción académica

## Creación de tipo de documento y workspace en Nuxeo

Se corrigen errores de envío de archivos a través de Nuxeo creando un nuevo tipo de documento y un Workspace para realizar peticiones a Nuxeo, dicho tipo de documento será exclusivo para documentos de solicitudes de docentes

![image](https://user-images.githubusercontent.com/44172561/99602187-0e4f9e00-29cf-11eb-934b-b1d68db9ddaf.png)

## Correcciones de envío de archivos

Se corrige el envío precipitado de archivos hacia Nuxeo debido a que se estaban enviado archivos a nuxeo y luego se sacaba una confirmación de la petición al docente, se modifico de tal forma que primero saldrá el mensaje de verificación y en caso de confirmar el envió se realiza el envió de los datos y además los archivos a Nuxeo.

![image](https://user-images.githubusercontent.com/44172561/99603101-a0a47180-29d0-11eb-9dd0-85cab9772812.png)

**Comment by CrissUD** [comment]
# Prueba Local de envió de producción académica

## Uso de Apis Locales

Se realizan pruebas locales para realizar el envió de una petición de producción académica, para realizar la prueba se corre de manera local las apis de **produccion_academica_crud** y **sga_mid**:
![apis](https://user-images.githubusercontent.com/44172561/99602053-bf096d80-29ce-11eb-93fa-95a73eeb8673.png)

# Resultado de envío de información 

Se hace una prueba para el envío de un articulo completo como producción académica de forma local.

![screencapture-localhost-4200-2020-11-18-18_58_11](https://user-images.githubusercontent.com/44172561/99602905-4dcaba00-29d0-11eb-8637-0e36e1af644f.png)

El resultado muestra el correcto envió y guardado en la base de datos 
* Tabla **produccion_academica**
![image](https://user-images.githubusercontent.com/44172561/99603223-e06b5900-29d0-11eb-8c60-f32a47ff115c.png)

* Tabla **autor_produccion_academica**
![image](https://user-images.githubusercontent.com/44172561/99603290-fed15480-29d0-11eb-8510-85e137e1d820.png)
* Tabla **metadato_produccion_academica**
![image](https://user-images.githubusercontent.com/44172561/99603349-17416f00-29d1-11eb-95ed-1782177cfbdf.png)

**Comment by CrissUD** [comment]
# comentario de prueba

**Comment by CrissUD** [comment]
- Mockups de listado de solicitudes (docencia, secretaría)
- Mockups de consultar solicitud
- Mockup de modificar solicitud

**Comment by CrissUD** [comment]
# Integración ProduccionAcademicaCliente con SolicitudCrud

Se realiza una modificación al modulo de envío de producción académica para que pueda guardarse también la solicitud al momento de envío de información. Con esta modificación el cliente envía la información requerida a **sga_mid** para registrar una producción académica y una vez esta fue registrada se obtiene el Id de registro y se procede a utilizar de nuevo a **sga_mid** para realizar el registro de una solicitud docente:

![code](https://user-images.githubusercontent.com/44172561/100449805-8b8baa80-3082-11eb-9d65-0ccf86ce7307.png)


Además se realizan algunos ajustes con alertas para que el usuario tenga indicaciones de cuando deba esperar y cuando fue creada una solicitud:
![image](https://user-images.githubusercontent.com/44172561/100449999-ddcccb80-3082-11eb-8ee3-0b1ad47eb768.png)
![image](https://user-images.githubusercontent.com/44172561/100450011-e7563380-3082-11eb-8e55-f7fc09cd9cb8.png)

**Comment by CrissUD** [comment]
# Vista inicial de solicitud y filtrado de tipo de producción académica

Como se estableció en los diseños de Mockups, se genera una vista que será la vista inicial en donde el docente podrá elegir que tipo de solicitud quiere enviar:
![image](https://user-images.githubusercontent.com/44172561/100450213-41ef8f80-3083-11eb-9413-43caa466faa6.png)

Sale además una ventana emergente donde se pide confirmación de parte del docente de cumplimiento de estatuto de propiedad intelectual de la Universidad, además de recomendación para juntar varios archivos PDF (esto solicitado por oficina de docencia):
![image](https://user-images.githubusercontent.com/44172561/100450435-a01c7280-3083-11eb-9cff-e458fb05b757.png)

Esto generará un filtrado adicional para los tipos de solicitudes que va a escoger el docente una vez haya escogido la categoría de solicitud respectiva:
![image](https://user-images.githubusercontent.com/44172561/100450505-c6421280-3083-11eb-9c38-c5846eb3f4bd.png)

**Comment by CrissUD** [comment]
# Listado de solicitudes docencia

Se refactoriza el componente **list_produccion_academica** el cual estaba generando varios errores, y además estaba trayendo el listado únicamente de las producciones académicas registradas. Se realiza una interacción con **sga_mid** para poder obtener información de las solicitudes docentes generadas por un tercero (en este caso un docente) que a su vez tiene anclada una producción académica, de esta forma se puede ver en el listado información relevante de la solicitud y de la producción académica que tiene dicha solicitud:
![image](https://user-images.githubusercontent.com/44172561/100450831-4d8f8600-3084-11eb-82ea-b1caaf9f9ff4.png)

Además se ajustan varios aspectos como las posibles acciones para cada solicitud, el alto de cada columna en la tabla, una alerta de espera mientras se carga la información etc:
![image](https://user-images.githubusercontent.com/44172561/100450916-80397e80-3084-11eb-866e-8294b0b7d71e.png)

**Comment by CrissUD** [comment]
# Mockup de modificación de solicitud docente

Se realiza un ajuste al componente de **crud_produccion_academica** para el caso de modificación, primero se realizan ajustes para los inputs tipo select y file para que traiga la información de manera adecuada, además se pasa por input toda la información de una solicitud docente y no solo de la producción académica, finalmente se realizan varios ajustes en **sga_mid** y **produccion_academica_crud** para que la modificación sea posible. 

Datos cargados al formulario:
![image](https://user-images.githubusercontent.com/44172561/100452752-be846d00-3087-11eb-9762-dea1f84ea4c7.png)

**Comment by CrissUD** [comment]
# Consulta de solicitud docente

Se realiza el mockup para revisar una solicitud a detalle mostrando los datos mas relevantes, se utiliza el mismo principio de **crud_produccion_academica** para realizar el cargue de información de la solicitud y la producción académica que tiene anclada: 

![screencapture-localhost-4200-2020-11-27-08_10_45](https://user-images.githubusercontent.com/44172561/100452991-3357a700-3088-11eb-87a8-1f8e87692468.png)

En el apartado de **ver detalles de estado**, se muestra la información del estado actual de la solicitud:
![image](https://user-images.githubusercontent.com/44172561/100453076-584c1a00-3088-11eb-8bfb-d70e16a75f10.png)

El apartado **comentarios** es un componente externo en el cual se podrán visualizar los comentarios realizados a dicha solicitud, en este caso se prueba con otra información y esta sujeta a realizar ajustes

**Comment by fabianbarreto02** [comment]
Se revisa la issue se espera observar el funcionamiento en local cuando se realice el sprint
