### ISSUE TITLE
Cliente generación y revisión de comentarios y cambios de estado

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#27]

**Comment by CrissUD** [comment]
# Lógica de componentes de acuerdo al Rol 

De acuerdo al rol del perfil que ingresa al sistema, se crea una serie de lógica que ayuda a determinar que componentes o que lógica debe hacerse, a continuación se explican estos casos:

## Muestra de solicitudes
De acuerdo a la lógica de negocio un **docente** solo puede ver las solicitudes que el haya generado, mientras que el rol de **s
Secretaria docencia** y **administración docencia** deberían poder ver todas las solicitudes que se han subido por parte de todos los docentes:
* Perfil docente revisando sus solicitudes
![image](https://user-images.githubusercontent.com/44172561/101168505-8a6df680-3609-11eb-8938-d40a6c33de10.png)
* Perfil de secretaria o administración revisando todas las solicitudes de todos los docentes:
![image](https://user-images.githubusercontent.com/44172561/101168652-be491c00-3609-11eb-882d-cfc4621bb237.png)

## Producción y revisión de comentarios
Los comentarios pueden ser creados únicamente por el rol de **secretaria docencia**, mientras que la visualización de estos podrá realizarse por todos los roles:
* Revisión de solicitud desde el perfil de docente
![screencapture-localhost-4200-2020-12-04-08_31_05](https://user-images.githubusercontent.com/44172561/101169633-3bc15c00-360b-11eb-9c31-7df855be89df.png)
* Revisión de solicitud desde el perfil de secretaria docencia
![screencapture-localhost-4200-2020-12-04-08_28_25](https://user-images.githubusercontent.com/44172561/101169395-d8372e80-360a-11eb-944a-0fc98d31b1c7.png)

## Muestra de opciones en solicitud

Una vez se visualiza una solicitud existen 3 opciones que pueden realizarse 
* Modificación de la solicitud
* Rechazo de la solicitud
* Verificación de la solicitud

Estas 3 acciones se deben poder visualizar por parte del perfil de **secretaria docencia** o **administración docencia**, sin embargo, el perfil de **docente** solo podría visualizar la opción de modificación de la solicitud en caso en que la solicitud a revisar este en un estado de **espera por modificación**:
* Opciones para perfil de docente cuando el estado NO es **espera por modificación**:
![screencapture-localhost-4200-2020-12-04-08_41_14](https://user-images.githubusercontent.com/44172561/101170565-a757f900-360c-11eb-9360-541511b06d32.png)
* Opciones para perfil de docente cuando el estado es **espera por modificación**:
![screencapture-localhost-4200-2020-12-04-08_31_05](https://user-images.githubusercontent.com/44172561/101170670-c8204e80-360c-11eb-898f-8eef9dd04141.png)
* Opciones para perfil de secretaria y administración:
![screencapture-localhost-4200-2020-12-04-08_28_25](https://user-images.githubusercontent.com/44172561/101170826-f9008380-360c-11eb-983a-2d390bc33313.png)

**Comment by CrissUD** [comment]
# Gestión de Comentarios y estado de solicitud

Una vez se crea la lógica de componentes de acuerdo al rol, se procede a crear la lógica de envío de comentarios y cambios en el estado, primero se realiza toda la lógica en las apis **sga_mid** y **solicitudes_crud** para la generación de comentarios y visualización de los mismos, así como del cambio de estado en la solicitud y registro de la evolución de los estados de dicha solicitud. 

## Registro de observación

El perfil de **secretaría docencia** o **administración docencia** pueden realizar comentarios gracias al componente **crud-comentarios** creado en el cliente, en el pueden registrar el titulo y descripción de un comentario:
![image](https://user-images.githubusercontent.com/44172561/101171426-bee3b180-360d-11eb-82d5-1472660a51c2.png)
Una vez se registre un comentario sobre una solicitud esta pasara al estado de **Espera por modificación** (*Nota: Por ahora el estado es llamado evaluación, pero esta sujeto a cambios*)

Estado de solicitud docente antes de comentario:
![image](https://user-images.githubusercontent.com/44172561/101171752-39143600-360e-11eb-8e43-293ff656694e.png)
Generación de comentario:
![image](https://user-images.githubusercontent.com/44172561/101171967-84c6df80-360e-11eb-9b3f-a290a7872b7b.png)
Estado de solicitud docente después de comentario:
![image](https://user-images.githubusercontent.com/44172561/101172041-9f995400-360e-11eb-8a26-03278beb649c.png)

## Visualización de comentario 
Se crea un componente **list-comentrios** el cual permite visualizar datos importantes de acuerdo al rol o componente a mostrar, Para el caso del perfil **docente** en el componente de revisión de solicitud, verá datos importantes como el título, fecha de observación y una acción para ver detalles:
![image](https://user-images.githubusercontent.com/44172561/101172311-028aeb00-360f-11eb-9a9b-707823fb575b.png)
Para el caso de los perfiles **secretaría docencia** o **administración docencia** se verán detalles como el título, la fecha de observación, la persona que creo la observación, el tipo de observación y una acción para ver el detalle de la observación:
![image](https://user-images.githubusercontent.com/44172561/101172618-64e3eb80-360f-11eb-8e68-394352e6e4a6.png)

Para el componente de modificación de solicitud se verán todos los detalles como el caso anteriormente explicado. Una vez se de click en el botón para ver detalles de observación podrá visualizarse una alerta de esta forma:
![image](https://user-images.githubusercontent.com/44172561/101172870-bc825700-360f-11eb-8895-5ff68ed83af1.png)


## Modificación de solicitud

Una vez se haga la modificación de la solicitud, el estado de la solicitud cambiará de nuevo por **Radicada**, de igual forma se guarda el registro del cambio de estado para tener presente toda la evolución de los estados de dicha solicitud:

* Estado de solicitud antes de modificación:
![image](https://user-images.githubusercontent.com/44172561/101173201-331f5480-3610-11eb-8b90-28f870a33435.png)
* Modificación de solicitud:
![screencapture-localhost-4200-2020-12-04-09_08_25](https://user-images.githubusercontent.com/44172561/101173336-6530b680-3610-11eb-9f96-8dcb11f1370c.png)
* Estado de solicitud después de modificación:
![image](https://user-images.githubusercontent.com/44172561/101173397-7b3e7700-3610-11eb-8580-e8e006e70709.png)

## Filtro de solicitudes

Se crea funcionalidad para filtrar solicitudes de acuerdo a su estado, esto gracias a un select que da opciones de filtrado al usuario:
* Todas las solicitudes:
![image](https://user-images.githubusercontent.com/44172561/101173549-b50f7d80-3610-11eb-8e8e-7fb497eeb5d0.png)

* Solicitudes en estado de radicación:
![image](https://user-images.githubusercontent.com/44172561/101173585-bccf2200-3610-11eb-9d85-7d25ce3ae34b.png)

* Solicitudes en estado por modificar:
![image](https://user-images.githubusercontent.com/44172561/101173623-c8224d80-3610-11eb-804c-a3ec0dd5934a.png)

**Comment by CrissUD** [comment]
Realizar ajustes con metadatos a drive.
Realizar mockup para invitación a par.

**Comment by CrissUD** [comment]
# Ajustes con metadatos a Drive

Se realiza un ajuste con los metadatos que están relacionados con la subida de archivos en Drive 

## Previsualización de archivos 

Se genera previsualización de documento para que el usuario docente pueda verificar que selecciono el archivo indicado y además como medio para dar a entender que se selecciono un archivo:
* Input para subir archivo a Drive antes de seleccionar archivo
![image](https://user-images.githubusercontent.com/44172561/101379054-d6c36b80-3881-11eb-8aa3-084ad6297617.png)
 * Input para subir archivo a Drive después de seleccionar archivo
![image](https://user-images.githubusercontent.com/44172561/101379164-f8bcee00-3881-11eb-868a-5123c2962302.png)
* Previsualización de archivo: 
![image](https://user-images.githubusercontent.com/44172561/101379230-0b372780-3882-11eb-94d9-afbeec4996f6.png)


## Visualización de archivos en Drive
El proceso de subida de archivos a drive se hace como un proceso interno ajeno a la funcionalidad de la página web, es por esto que el proceso de la subida del archivo puede demorarse un tiempo dependiendo del tamaño del archivo. En caso en que un usuario docente, secretaría o administración docencia consulte una solicitud en el que se ha subido un archivo a drive pero este aun no ha completado su carga, se vera un mensaje de la siguiente forma:
![image](https://user-images.githubusercontent.com/44172561/101380602-b8f70600-3883-11eb-80ad-ac7588805fa1.png)

Una vez la carga a drive se haya completado, en la solicitud puede verse la información de dicho documento de la siguiente forma: 
![image](https://user-images.githubusercontent.com/44172561/101381439-bf39b200-3884-11eb-9a49-4c4e3e2fdf56.png)

Una vez se da click en el link, puede verse el archivo subido en el drive:
![image](https://user-images.githubusercontent.com/44172561/101381720-1b043b00-3885-11eb-8d1b-bc636f28db94.png)

## Visualización de archivos para modificar

Igualmente cuando se va a modificar una solicitud, en caso de que el archivo no haya subido aun en Drive el input para seleccionar un nuevo archivo se verá sin ninguna novedad:
![image](https://user-images.githubusercontent.com/44172561/101381960-661e4e00-3885-11eb-9eda-adb032d6aab6.png)
En caso de haber cargado el archivo en Drive se verá de la siguiente forma: 
![image](https://user-images.githubusercontent.com/44172561/101382041-7df5d200-3885-11eb-9c73-adf76ab884f9.png)

**Comment by CrissUD** [comment]
# Generación de lógica para verificación y rechazo de Solicitudes

Se genera lógica para las acciones de verificación y rechazo de solicitudes:
![image](https://user-images.githubusercontent.com/44172561/101905076-dd552a00-3b84-11eb-9682-efb452eead91.png)

## Verificación de solicitudes
Una vez el personal de secretaría o administrador de docencia verifique una solicitud se tendrá que comprobar el tipo de producción académica ya que dependiendo de este factor, la solicitud podría entrar en un estado u otro: 
![image](https://user-images.githubusercontent.com/44172561/101905464-813ed580-3b85-11eb-9109-d9d4783ab97e.png)

Antes de realizar la verificación se pregunta al personal si esta seguro de realizar la verificación de la solicitud:
![image](https://user-images.githubusercontent.com/44172561/101905582-ad5a5680-3b85-11eb-8fb2-94da0f557d3d.png)

Una vez se verifica se realiza un cambio de estado de acuerdo a lo planteado en la imagen de los tipos de producciones, así por ejemplo si se verifica una solicitud cuya producción académica es de tipo patente será verificada inmediatamente:
![image](https://user-images.githubusercontent.com/44172561/101905797-ff9b7780-3b85-11eb-9cfb-d9d314a26c39.png)
![image](https://user-images.githubusercontent.com/44172561/101905846-1510a180-3b86-11eb-8b52-1ebc6b10dd30.png)

Para otra solicitud cuya producción académica sea una producción de video, cinematográfica o fonografía el estado cambiara a espera por evaluación por parte del par externo:
![image](https://user-images.githubusercontent.com/44172561/101906006-49845d80-3b86-11eb-81e6-2e2cc9011168.png)
![image](https://user-images.githubusercontent.com/44172561/101906071-61f47800-3b86-11eb-8e5c-b5d2da2678ed.png)


## Rechazo de solicitudes

El personal de secretaría o administración docencia podrá realizar el rechazo de una solicitud, en dado caso se tendrá que escribir un comentario indicando la razón del rechazo de la solicitud:
![image](https://user-images.githubusercontent.com/44172561/101906280-b1d33f00-3b86-11eb-8547-56c1d296696f.png)
![image](https://user-images.githubusercontent.com/44172561/101906301-bdbf0100-3b86-11eb-9f0d-63ac95a018a9.png)

De esta forma una vez la solicitud quede negada, el docente sabrá el motivo del rechazo: 

![image](https://user-images.githubusercontent.com/44172561/101906424-ec3cdc00-3b86-11eb-8a94-3b98c4c40082.png)

![image](https://user-images.githubusercontent.com/44172561/101906441-f4951700-3b86-11eb-86af-dececa22cbc5.png)

**Comment by CrissUD** [comment]
# Generación de componente para envío de invitación a evaluador par

Se genera el componente gráfico para enviar una invitación a par externo, se espera ensamblar lógica con servicio de **google_mid**  para realizar el envió de notificación a través de correo electrónico.
![image](https://user-images.githubusercontent.com/44172561/101906666-53f32700-3b87-11eb-9156-955b632c7843.png)

Dicho componente podrá ser visualizado únicamente si la solicitud esta en estado de **Para evaluación**

**Comment by fabianbarreto02** [comment]
Se issue se da por finalizada
