### ISSUE TITLE
Generación de mockups para fase 3

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#28]

**Comment by Camiloqui** [comment]
Inicialmente en el sga_mid en el controlador solicitud_docente, creamos un metodo tipo get one, donde nos devuelve peticiones de un mismo estado, en nuestro caso, el estado es el 4, pero el metodo funciona parar traer todas las funciones de un mismo estado, ya sea verificada, radicada, para evaluar, rechazada etc.... 
![image](https://user-images.githubusercontent.com/19983790/102630893-1d835200-411b-11eb-9f79-f739bc285641.png)
![image](https://user-images.githubusercontent.com/19983790/102630933-2bd16e00-411b-11eb-8b75-5e9ec10fb64f.png)
la variable v se imprime y es el mapa donde se guardan las solicitudes realizadas pro el docente que se encuentren en el estado que se pide.

**Comment by Camiloqui** [comment]
En produccion_academica_cliente, se crea una carpeta donde vamos a realizar la seccion que muestre una lista de solicitudes verificada.
![image](https://user-images.githubusercontent.com/19983790/102631169-6dfaaf80-411b-11eb-9106-0c18e8ad4bc6.png)
Esta tiene 3 metodos importantes loadData, ShowData y cargarCampos.
Inicialmente empezaremos explicando loadData, en esta se inicia con una promesa para que cuando se llame la funcion se devulevan los datos cuando la promesa se cumpla, 
![image](https://user-images.githubusercontent.com/19983790/102631420-aef2c400-411b-11eb-8d07-c75b876bc749.png)
simplemente en el endpointSolicitud apuntamos al sga_mid al controlador creado y le mandamos el Id del estado que buscamos en este caso es el 4, y apartir de ahi buscamos el campo referencia en el cual es la produccion academica relacionada con la solicitud asi que debemos buscarle la produccion y agregarsela al objeto obtenido, cuando se tengan todas las producciones en cada objeto la promesa se cumple y regresa el objeto del total de arrays con los datos solicitados. 
En showdata()
![image](https://user-images.githubusercontent.com/19983790/102631697-0d1fa700-411c-11eb-98e9-880b828d433e.png)

Tiene un swal que muestra un texto de esperar informacion mientras la promesa de loadData termina, cuando la promesa de load data, el swal se cierra y coge el objeto formado por load data y lo asigna al arreglo global que luego sera llamado en cargar datos

En CargarDatos
![image](https://user-images.githubusercontent.com/19983790/102631853-435d2680-411c-11eb-83b1-a4d72d2a53bc.png)

![image](https://user-images.githubusercontent.com/19983790/102631889-4c4df800-411c-11eb-88ff-ef6859c6e7d1.png)

en este metodo, cargamos de manera individual los campos de cada solicitud, pero como son demasiados datos solamente traemos los importantes a mostrar, como titulo, fecha de radicacion, fecha limite etc etc... tambien carga un filtro de solicitudes que de momento solamente muestra las solicitudes verificadas, pero la idea es cambiarlo para que filtre las solicitedes radicadas por fechas, y asi tener un control de las solicitudes totales.

**Comment by Camiloqui** [comment]
mostraremos visualmente que muestra en produccion academica
![image](https://user-images.githubusercontent.com/19983790/102632959-c7fc7480-411d-11eb-9bc7-d34c4763f002.png)
 se muetra en el menu la nueva opcion de las solicitudes aprobadas
y tambien las solicitudes con estado verificada 
![image](https://user-images.githubusercontent.com/19983790/102636504-b8cbf580-4122-11eb-8010-4680d973b58a.png)

**Comment by CrissUD** [comment]
# Generación de paquetes

Una vez creado el filtro para solicitudes que han sido verificadas, se genera una casilla extra donde se pueden seleccionar que solicitudes van a entrar para el próximo comité, esta consiste en una serie de checkbox donde el personal de secretaría o administración de la oficina de docencia podrán escoger las solicitudes: 
![image](https://user-images.githubusercontent.com/44172561/103229007-297fc880-4900-11eb-9e1b-25a03005d2b6.png)

Además se genera una casilla en donde el usuario tiene la posibilidad de seleccionar todas las solicitudes de inmediato
![image](https://user-images.githubusercontent.com/44172561/103229073-5207c280-4900-11eb-9d04-c310ae67353b.png)

Se adiciona también un filtrado de solicitudes de acuerdo al tipo de puntaje que requiere la solicitud, siendo estas salariales o de bonificación, esto debido a petición de oficina de docencia ya que manifiesta que es común la revisión de comités por tipos de puntajes:
![image](https://user-images.githubusercontent.com/44172561/103229283-bcb8fe00-4900-11eb-8631-fb71adf0e0a2.png)


Una vez se hayan seleccionado las solicitudes, es posible generar el próximo paquete que ira a comité con el botón generación paquete: 
![image](https://user-images.githubusercontent.com/44172561/103229178-867b7e80-4900-11eb-9f45-901ae6c31f27.png)

En caso de no seleccionar ninguna solicitud el sistema genera una alerta:
![image](https://user-images.githubusercontent.com/44172561/103229359-d9553600-4900-11eb-9154-3106a67cbb25.png)

En caso de selección de solicitudes el sistema primero pregunta si esta seguro de la generación del paquete:
![image](https://user-images.githubusercontent.com/44172561/103229455-07d31100-4901-11eb-8efc-aa72b5aa7ba0.png)

Una vez se acepte, pedirá unos datos adicionales como el número y fecha del siguiente comité:
![image](https://user-images.githubusercontent.com/44172561/103229515-289b6680-4901-11eb-94ee-84241e110446.png)

Una vez aportado estos datos el sistema se encargará de crear el paquete y finalmente generara un mensaje con el éxito de la creación del mismo
![image](https://user-images.githubusercontent.com/44172561/103229581-597b9b80-4901-11eb-81b9-b03bb32a16e7.png)

**Comment by CrissUD** [comment]
# Lista de paquetes para revisión en comité

Se genera un nuevo modulo que estará disponible únicamente para la administración de la oficina de docencia, dentro de este se crean además algunos componentes como un listado de paquetes y un listado de solicitudes que hacen parte de un paquete:
![image](https://user-images.githubusercontent.com/44172561/103229856-f0e0ee80-4901-11eb-905d-6293265c5f16.png)

Dentro del componente **list-paquetes** se genera un listado donde puede verse la información principal de los paquetes, entre estos datos están:
* Numero de Comité
* Fecha de Comité
* Estado de Comité (por revisar, revisado)
* Numero de solicitudes que contiene
Además de una acción para ver con detalle el contenido de cada uno de los paquetes;
![image](https://user-images.githubusercontent.com/44172561/103230128-a744d380-4902-11eb-8f84-7cac03875525.png)

**Comment by CrissUD** [comment]
# Lista de solicitudes dentro de cada paquete

Se genera mockup que trae el listado de todas las solicitudes que están dentro de un paquete seleccionado:
![image](https://user-images.githubusercontent.com/44172561/103230876-7d8cac00-4904-11eb-8e64-9221a3ef6fcb.png)

Nota: Faltan algunos detalles para este mockup

**Comment by CrissUD** [comment]
# Actualización cliente para fase 3 

## Generación opciones por solicitud
Se agregan nuevas opciones en la tabla para realizar sobre cada solicitud de un paquete, en este caso se agregan las opciones de:
* Revisar: donde se podrá ver a detalle la solicitud y en caso de ser necesario comentar algún cambio que deba hacerse
* Aplazar: donde se saca una solicitud del comité actual debido a algún cambio grande que debe hacerse por parte del docente y estará sujeto a reintegración en un próximo comité
* Rechazar: donde se cambia el estado de la solicitud con un puntaje de 0 y en el cual se envía un comentario sobre la razón del rechazo
* Modificar: donde se podrán cambiar algunos datos de la producción pertinentes dichas por el comité

![image](https://user-images.githubusercontent.com/44172561/103491861-1041b500-4df5-11eb-9808-ffd1fceb3860.png)

## Generación de opciones para generación de reportes

Se agregan opciones que sirven para soportar la lógica de generación de reportes y además de gestión de cambios de estados:
![image](https://user-images.githubusercontent.com/44172561/103491961-a1b12700-4df5-11eb-9c0b-5eac9962ff20.png)

**Comment by CrissUD** [comment]
# Lógica de estados dentro de paquetes

Se genera la lógica de estado con solicitudes que están dentro de un paquete, esto debido a que el estado en este punto cambiará para la solicitud y también para la relación solicitud-paquete existente en el modelo de datos, siendo estos los siguientes casos:
* Generación de comentario a solicitud dentro de paquete
* Modificación de solicitud dentro de paquete
* Rechazo de solicitud dentro de paquete
* Aplazamiento de solicitud dentro de paquete
* Generación de acta después de reunión con comité
* Aceptación de acta generada

## Generación de comentario a solicitud dentro de paquete
Cuando se revise una solicitud a detalle y se genere un comentario esta pasara a un estado llamado **"En revisión previa al comité"** y se debe esperar a realizar cambios pertinentes antes de la generación del acta
## Modificación de solicitud dentro de paquete
Cuando se realicen los respectivos cambios a una solicitud dentro del paquete volverá al estado inicial dentro del paquete llamado **"Caso Seleccionado"**
## Rechazo de solicitud dentro de paquete
Cuando se realice un rechazo de solicitud dentro del paquete  volverá al estado inicial dentro del paquete llamado **"Caso Seleccionado"** y el resultado del puntaje será de 0
## Aplazamiento de solicitud dentro de paquete (Falta)
Se espera que el estado de la solicitud cambie al estado numero 2 y se elimine la relación solicitud-paquete existente
## Generación de acta después de reunión con comité
Se cambia el estado de todas las solicitudes del paquete y la relación de las mismas con el paquete por el estado **"Tratado en el comité"**
## Aceptación de acta generada
Se cambia el estado de todas las solicitudes del paquete y la relación de las mismas con el paquete por el estado **"Acta Aprobada"**

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
