### ISSUE TITLE
Incorporación de cliente con servicio de correo y generación de vista para respuesta de par

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#39]

**Comment by CrissUD** [comment]
# Lógica en cliente para envió de notificaciones por correo

Una vez la solicitud este en el estado **Para evaluación** el personal secretario o administración podrá ver el componente para envío de invitación a par externo: 
* Lista de solicitudes en estado de Para evaluación:
![image](https://user-images.githubusercontent.com/44172561/102561512-ebcea480-40a2-11eb-9635-106bd9b1a2f8.png)
* Revisión a detalle de solicitud que necesita ser evaluada: 
![image](https://user-images.githubusercontent.com/44172561/102561545-0274fb80-40a3-11eb-8f23-aad6a4098cd0.png)
*Una vez se complete la información saldrá un mensaje pidiendo confirmación del usuario:
![image](https://user-images.githubusercontent.com/44172561/102561763-84fdbb00-40a3-11eb-9d2f-3df626b9d776.png)
* Una vez se confirma se enviará un correo al par externo con la siguiente estructura: 
![screencapture-mail-google-mail-u-2-2020-12-17-20_08_51](https://user-images.githubusercontent.com/44172561/102561966-09503e00-40a4-11eb-9643-dfc082a82f05.png)
* Finalmente se cambia el estado de la solicitud a **en espera par**
![image](https://user-images.githubusercontent.com/44172561/102562384-f68a3900-40a4-11eb-8a16-a15da1ba52e5.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
