### ISSUE TITLE
Realizar flujo de inscripción de pares externos y agregación de información complementaria de pares

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#46]

**Comment by EstefaniaPerezTorres** [comment]
### Inscripción a pares externos
_Para que un par externo realice la inscripción a Terceros se utilizaron dos componentes, inscripción (pre inscripción) e info_persona (crud-info_persona)._
 
1. Primero se da la opción en el menú para esta inscripción
![image](https://user-images.githubusercontent.com/72519041/103551199-04e39d80-4e78-11eb-9d5c-51bb565fae0a.png)
2. Al ingresar a dicha opción se carga el componente de pre inscripción el cual obtendrá el ID del usuario que ingreso al sistema. Esto se hace en el método de **loadData()** que es llamado desde el constructor del componente.
![image](https://user-images.githubusercontent.com/72519041/103551009-b2a27c80-4e77-11eb-908b-cd6b6e176662.png)
3. Se llama el componente de crud-info_persona y se le pasa por parámetro el ID del usuario y este componente carga los campos del formulario con el método **construirForm()** que el llamado en el constructor, así mismo, se cargan las lista que van en los select del formulario.
![image](https://user-images.githubusercontent.com/72519041/103551311-293f7a00-4e78-11eb-880f-d36bc19a6116.png)
![image](https://user-images.githubusercontent.com/72519041/103551915-0feafd80-4e79-11eb-8835-b66779aa24bb.png)
4. Este componente llama el método de **validarForm()** que valida que la inscripción sea indefinida para llamar el método de **validarTerminos()** donde se creara la información del tercero
![image](https://user-images.githubusercontent.com/72519041/103551496-6b68bb80-4e78-11eb-8f9a-aa186666467e.png)
![image](https://user-images.githubusercontent.com/72519041/103552104-622c1e80-4e79-11eb-9f9a-d3ab32b32e3d.png)
5. La información se crea en el método de **createInfoPersona()** que llama el servicio de **sga_mid/persona/guardar_persona**
![image](https://user-images.githubusercontent.com/72519041/103552345-c0590180-4e79-11eb-8250-eea1f98bb1f6.png)

**Comment by EstefaniaPerezTorres** [comment]
### Solución de problema con la inscripción a Terceros
_Hay que aclarar que estos componentes fueron copiados del cliente de SGA_

Al probar la funcionalidad recién copiados del cliente de SGA se estaba generando un error al llamar al servicio de persona/guardar_persona en SGA_MID, según la consola era un problema de formato de fechas, por esto se hizo un cambio en el cliente de producción académica y otro en el sga_mid

1. produccion_academica_cliente
En el método de **createInfoPersona()**, antes de llamar el servicio de sga_mid se asigna la fecha de nacimiento, de expedición y el usuario, esas dos fechas ahora tienen el siguiente formato
![image](https://user-images.githubusercontent.com/72519041/103553215-23976380-4e7b-11eb-94e8-dc8d70bd53aa.png)

2. sga_mid
En el método de **guardar_persona()** se realiza el cambio en el mapeo correspondiente a cada fecha
![image](https://user-images.githubusercontent.com/72519041/103553537-943e8000-4e7b-11eb-9e03-183115a52201.png)

> También se limpiaron los componentes copiados eliminando los métodos, atributos e imports que no fueron necesarios para la creación de la información en terceros

**Comment by fabianbarreto02** [comment]
queda pendiente el registro de la información complementaria

**Comment by Camiloqui** [comment]
**inserts de informacion complementaria en terceros_Crud**
se realiza la creacion de los inserts del nueva informacion en las tablas grupo_info_complementaria e info_complementaria
inicialmente se creo el insert del grupo que en este caso seria informacion par academico 
![image](https://user-images.githubusercontent.com/19983790/103680106-4e50ed00-4f4b-11eb-98a3-bf0ecc0dadaa.png)
![image](https://user-images.githubusercontent.com/19983790/103680168-6163bd00-4f4b-11eb-8916-b807c8aa1ab6.png)
donde el id asigando es el 20, y el nombre es informacion evaluador par, este id nos sirve para agregar la infofmacion complementaria dicha informacion es institucion area de conocimento y formacion academica:
![image](https://user-images.githubusercontent.com/19983790/103680266-89ebb700-4f4b-11eb-9136-4e104db7ed69.png)
![image](https://user-images.githubusercontent.com/19983790/103680292-92dc8880-4f4b-11eb-8031-7f6dc3fab707.png)

se linkea el pull request esperando ser aceptado por jhon para pasar la migracion 
[https://github.com/udistrital/terceros_crud/pull/62](url)

**Comment by Camiloqui** [comment]
### **Logica SGA_mid para subir la informacion a Terceros**
**Se crea un nuevo controllador en Persona**
Al controlador le llegara un json con el tercero que asignara la informacion, la informacion complementaria, son 4 campos principales del json, inicialmente busca el tercero al cual le va a realizar la insercion de informacion complementaria del par academico, luego separa del json la informacion que necesita para el primero item de infor complementaria en ese caso es "area de conocimiento" hace un post a terceros creando la nueva informacion en la tabla, luego realiza el mismo proceso con los otros dos datos faltantes, en caso de que haya algun error dentro de algun post en el else se borrara el dato errroneo ya que podria haber duplicidad de datos.
![image](https://user-images.githubusercontent.com/19983790/104971668-115a1100-59b5-11eb-9857-f2083c5d85d2.png)

**Comment by Camiloqui** [comment]
**En el cliente se crea un nuevo apartado llamado informacion complementaria**
![image](https://user-images.githubusercontent.com/19983790/104971888-c55b9c00-59b5-11eb-9206-ac6ac6cb7c34.png)
Aca el par academico al momento de registrarse pondra su area de conocimiento dentro de colciencias, su nivel de formacion y la institucion a la que pertenece, intermente el modulo busca el tercero del apartado de recien creado, y forma el json que necesita recibir el sga_mid de la siguiente manera
![image](https://user-images.githubusercontent.com/19983790/104972012-284d3300-59b6-11eb-8b5b-f3090e873003.png)

de momento se registrara con el tercero id 1 ya que mi usuario cequiroam no se encuentra registrado en terceros

**codigo dentro de cliente**

se crea un nuevo componente con ayuda de ng 
![image](https://user-images.githubusercontent.com/19983790/104972114-706c5580-59b6-11eb-9dcb-270b44c324d8.png)

En el html colocamos los select que necesitamos y el input para el apartadod e institucion con su respectivo translate.
![image](https://user-images.githubusercontent.com/19983790/104972224-b5908780-59b6-11eb-9657-fcd5852740b2.png)
**En el componente se crean metodos para obtenes la informacion de area de conocimiento y nivel de formacion**

dicha info la trae de las apis proyecto academico crud y parametros crud, tambien trae info de teceros de que campos son los que va a insertar de infocomplementaria 

![image](https://user-images.githubusercontent.com/19983790/104972448-64cd5e80-59b7-11eb-9f9c-4a92eb7ad27e.png)

**Comment by fabianbarreto02** [comment]
Falta servicio de cambio roll

**Comment by Camiloqui** [comment]
se agrega una funcionalidad para que si el par ya registro su informacion complementaria esta se llene automaticamente 
![image](https://user-images.githubusercontent.com/19983790/106209549-d90fbb00-618a-11eb-9641-2006a4cc54dc.png)

**Comment by fabianbarreto02** [comment]
Pendiente aun el servicio de cambio del roll

**Comment by Camiloqui** [comment]
**Cambio de rol**
![image](https://user-images.githubusercontent.com/19983790/107061578-f998d000-679d-11eb-91d3-94e37c890fba.png)
Cuando el usuario usa el modulo de inscripcion, y crea sus datos personales, se envia el post de cambio de rol, donde se selecciona el usuario que tiene en el momento y le agrega el rol "EVALUADOR" el proceso interno desarrollado por Jhon y compañia, realiza el cambio dentro del perfil del usuario ws2, y asigna el perfil en autenticacion.

Dentro del sistema se puede observar los roles que tiene el usuario 
![image](https://user-images.githubusercontent.com/19983790/107062121-90658c80-679e-11eb-9773-ae361a42e1a7.png)
en la consola, ya de esta manera queda completado la asignacion del rol.


**ajuste de modulo de informacion complementaria**

El modulo funciona bien, pero al momento de que un usuario tenga informacion en la base de datos, no traia la informacion completa solo uno o dos de los 4 campos se resuelve la inquietud para que siempre traiga los 4 elementos
![image](https://user-images.githubusercontent.com/19983790/107062316-ca369300-679e-11eb-9431-5ead2407a655.png)

Para poder realizar esto se tuvo que separa los procesos, al parecer en cada find no dejaba que otra lista buscara informacion, se separo en dos metodos y funciona perfectamente, el nuevo metodo es  loadInfoGrupoAcademico()
![image](https://user-images.githubusercontent.com/19983790/107062423-e6d2cb00-679e-11eb-82ba-5cba7f19c79b.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
