### ISSUE TITLE
Lógica aplazamiento solicitudes dentro de paquete

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#50]

**Comment by EstefaniaPerezTorres** [comment]
### Migración de estado "APLAZADA" en solicitud_crud
Se agrega estado de APLAZADA en _solicitud_estado_ y en _estado_tipo_solicitud_ se agrega con el tipo de solicitud 1.

![code](https://user-images.githubusercontent.com/72519041/103959581-0fbf5c00-511e-11eb-8b21-8bda3d57b571.png)

> Archivos que empiezan por: 20210105_093842

**Comment by EstefaniaPerezTorres** [comment]
### Método para aplazar la solicitud
Se agrega método `postponeSolicitud` en componente _list-solicitudes-paquete_
![code](https://user-images.githubusercontent.com/72519041/103959980-287c4180-511f-11eb-80c0-71faeb6abf7c.png)

**Comment by fabianbarreto02** [comment]
se da por finalizda la issue
