### ISSUE TITLE
Ajustes cliente

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#51]

**Comment by EstefaniaPerezTorres** [comment]
### Migración de estado "APLAZADA" en solicitud_crud
Se agrega estado de APLAZADA en _solicitud_estado_ y en _estado_tipo_solicitud_ se agrega con el tipo de solicitud 1.

![code](https://user-images.githubusercontent.com/72519041/103959581-0fbf5c00-511e-11eb-8b21-8bda3d57b571.png)

> Archivos que empiezan por: 20210105_093842

**Comment by CrissUD** [comment]
# Ajuste de actualización de estado en envío de invitación

Se realizan ajustes sobre actualización de estado para envío de invitación, al primer envío se genera el cambio de estado a **en espera par** pero a partir de ahí no se debe generar ningún cambio de estado 

![ajuste1](https://user-images.githubusercontent.com/44172561/103959913-fc60c080-511e-11eb-872b-ccb65410427c.png)

**Comment by CrissUD** [comment]
# Generación de visualización y  modificación de resultado de una solicitud

Se genera logica para la visualización y modificación de resultados en caso de que una solicitud ya cuente con un puntaje, dicho puntaje puede ser visualizado unicamente por perfiles de secretaria y administracion docencia, ademas se agrega logica de estados para que no produzca actualizacion de estado por cambio de resultados en casos especificos

![image](https://user-images.githubusercontent.com/44172561/103960769-f1a72b00-5120-11eb-8db5-0706a9f9e89c.png)

![image](https://user-images.githubusercontent.com/44172561/103960816-100d2680-5121-11eb-924d-0943de67e8f9.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada
