### ISSUE TITLE
Generación flujo proceso de evaluaciones

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#53]

**Comment by CrissUD** [comment]
# Generación de Formularios para evaluación

Una vez creados los inserts correspondientes en la Api **evaluaciones_crud** se procede a la generación de formularios para evaluación a través de **formularios dinámicos**.

## Generación Formulario Dinámico 

Los formularios de evaluación al componerse en secciones que a su vez están compuestas por campos requieren de la creación de lógica adicional para soportar esta estructura:
![dinamicform](https://user-images.githubusercontent.com/44172561/104727881-16446980-5704-11eb-9b6c-bb1e524931b8.png)
Como se muestra en la imágen se crea un nuevo tipo de formulario dentro del switch case del componente, este formulario llamado **form-eval** se caracteriza por soportar la estructura form -> secciones -> campos, además se tiene en cuenta otro tipo de etiquetas que hacen parte del formulario pero no son inputs tales como h3, h4, p etc.

Por otro lado se tuvo que modificar lógica del componente para que tenga en cuenta la estructura del nuevo formulario creado
![dinamicform2](https://user-images.githubusercontent.com/44172561/104728626-2b6dc800-5705-11eb-8086-522a67f9c609.png)

## Obteniendo información de los formularios

La información contenida en **evaluaciones_crud** es obtenida y tratada para generar la estructura de los formularios, dicha consulta se realiza a través del nombre del **tipo de evaluación** que coincide con el nombre del tipo o subtipo de producción que se va a evaluar: 

![loadForm](https://user-images.githubusercontent.com/44172561/104728848-83a4ca00-5705-11eb-9099-e37a5c666d04.png)

## Resultado generación de formularios

A continuación se muestra la generación de formularios para el registro de evaluaciones:
![screencapture-localhost-4200-2021-01-15-08_00_44](https://user-images.githubusercontent.com/44172561/104730437-09c21000-5708-11eb-96de-6dff5c77380c.png)
![screencapture-localhost-4200-2021-01-15-08_03_35](https://user-images.githubusercontent.com/44172561/104730626-658c9900-5708-11eb-8386-f34b330b42e6.png)

**Comment by CrissUD** [comment]
# Lógica adicional para la generación de formularios

Existen algunas particularidades en los formularios de evaluación que se requieren de una lógica adicional

## Generación de evaluación para traducción de libros

Este tipo de producción no cuenta con un formulario especifico, sino que comparte el formulario con la producción de libros, es por esto que se genera un query diferente para este caso de producción:
![traduccion](https://user-images.githubusercontent.com/44172561/104731017-12671600-5709-11eb-9bd1-de68ba0a631a.png)

# Filtrado de secciones
Existen algunos formatos de evaluación que cuentan con mas de una sección sin embargo a la hora de mostrar el formulario solo se puede mostrar una de estas dependiendo de datos específicos de la producción académica a evaluar.
Un ejemplo de estos es el formulario de evaluación para producciones de video, Cinematografica o fonografía que muestra una sección de pendiendo si la producción es de tipo documental o dinamica, y muestra otra sección si es una producción nacional o internacional:
![filtroSecciones](https://user-images.githubusercontent.com/44172561/104731548-d97b7100-5709-11eb-8408-6000cf4a0f3c.png)

**Comment by CrissUD** [comment]
# Generación de evaluación y cambio de estado 

## Lógica para creación de evaluación y cambio de estado

Con los formularios realizados, se procede a generar la lógica para la creación y registro de la evaluación asi como la actualización de estado en la solicitud de evaluación:

![validform](https://user-images.githubusercontent.com/44172561/104738088-126c1380-5713-11eb-805d-0ce92a5792e5.png)

Con esta lógica se valida que la información del formulario este completa y se procede a construir el arreglo de respuestas que integra el objeto de evaluación, una ves se construyen las respuestas se crea el objeto de la evaluación para ser registrado:

![crearevaluacion](https://user-images.githubusercontent.com/44172561/104738556-ab9b2a00-5713-11eb-97e7-c99cecb8c4e3.png)

Una vez creada y registrada la evaluación el **evaluacion_crud** se procede a realizar la actualización de estado de la solicitud que va a referenciar dicho registro de evaluación:
![actualizarsolicitud](https://user-images.githubusercontent.com/44172561/104738871-10568480-5714-11eb-984e-ca943f078f26.png)

## Resultados
Validación de campos no llenados
![image](https://user-images.githubusercontent.com/44172561/104739840-34ff2c00-5715-11eb-80b4-c11a5077854a.png)
Validacion de campos del evaluador
![image](https://user-images.githubusercontent.com/44172561/104739914-4ea07380-5715-11eb-8d69-0a88b4a22a4d.png)
Pregunta para asegurar registro
![image](https://user-images.githubusercontent.com/44172561/104739995-6841bb00-5715-11eb-924b-fa6c3c3681c8.png)
Mensaje de exito en el registro
![image](https://user-images.githubusercontent.com/44172561/104740171-9d4e0d80-5715-11eb-86c2-86148f78856a.png)

**Comment by CrissUD** [comment]
# Generación de mockup para visualización de evaluaciones

Se genera vista para poder visualizar las evaluaciones realizadas por parte de los pares externos:

Una vez la evaluación se haya registrado en el sistema, cuando se consulte la solicitud de la cual se realizo dicha evaluación esta podrá verse en el listado de inviaciones de evaluación con el estado de "Evaluada":
![image](https://user-images.githubusercontent.com/44172561/104741393-20239800-5717-11eb-91b8-1b358fdb3b05.png)

Una vez se de en la lupa para visualizar la evaluación se abre un pop up que muestra los datos de la evaluación:

Datos de evaluación de videos
![image](https://user-images.githubusercontent.com/44172561/104741515-519c6380-5717-11eb-909a-1602f70c0951.png)
![image](https://user-images.githubusercontent.com/44172561/104741525-55c88100-5717-11eb-926e-ea15c64f0012.png)

Datos de evaluación de libros
![image](https://user-images.githubusercontent.com/44172561/104741620-74c71300-5717-11eb-8627-8cf1f442cd36.png)

Datos de evaluación de Software
![image](https://user-images.githubusercontent.com/44172561/104741693-890b1000-5717-11eb-9206-d0234d2fb4cf.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue, falta aprobación por parte del usuario a cambio de mockup y inclusión de la firma
