### ISSUE TITLE
Realizar lógica para traer información de títulos del docente

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#54]

**Comment by Camiloqui** [comment]
### **Modificacion de Tabla Info_complementaria_tercero**
**Creacion de migrations**

Se crea inicialmente la migracion con comandos de bee, y en los apartados de up() y down() se le asigna el codigo de script que deberia ser creado en la carpeta de scripts

![image](https://user-images.githubusercontent.com/19983790/104968804-7b21ed00-59ac-11eb-87c1-87d526972a4c.png)

**En el script up()**
se modifica la tabla ya señalada y se le agrega la columna info_complementaria_tercero_padre_id y se le crea la relacion de llave foranea para ser llamada a ella misma
![image](https://user-images.githubusercontent.com/19983790/104968894-bcb29800-59ac-11eb-9dea-d34ea3db6434.png)

**En el script down()**
se eliminara la relacion fk que tiene la llave si existe y luego borra la columna para no tener problemas 
![image](https://user-images.githubusercontent.com/19983790/104968978-f8e5f880-59ac-11eb-8d37-c5e92e7c4332.png)


**Modificacion del modelo**
Se modifica el modelo agregando una nueva columna en este caso la llamaremos InfoCompleTercerosPadreId para que no quede tan larga y la relacionamos como fue llamada debidamente en la base de datos
![image](https://user-images.githubusercontent.com/19983790/104969073-2a5ec400-59ad-11eb-98be-c2475c95825b.png)

Tambien la dejas como null para que los demas campos no sean modificados y no presente problemas con alguna otra informacion.

### Creacion de Metodo en el controlador
al metodo se llama postPadre() su ruta sera /info_complementaria_terceros/padre a ese endpoint se realizaran los post padre que se requieran

El metodo crea una variable (v) basado en el modelo infoComplementariaTerceros y agrega la informacion del post a una variable tipo map[string]intertace{}
Luego busca dentro del map el tercerdo Id y el campo padre que para el caso de informacion academica sera "ProgramaAcademico" luego este asigna a la variable v los campos respectivos de tercero id, infoComplementariaId y el dato, se hace la subida de informacion a la base de dato y retornara la v con el id asignado, luego de esto, a los demas campos que se requiera se realizara el mismo proceso inicial pero en el campo del modelo "InfoCompleTerceroPadreId" se le asignara la variable v que realmente es basado al modelo asi que es un map que se puede asignar sin problemas, pasado este paso se hara la agregacion en cascada de cada dato que necesite su padre id  **Este metodo solo funciona para el caso de agregar el grupo 18 que es informacion academica, aun no se ha creado un metodo general que pueda ser usado para los demas grupos complementarios que requieran padre id**
![image](https://user-images.githubusercontent.com/19983790/104969412-f6d06980-59ad-11eb-8b75-b07b624a911b.png)

### Formato json de como se deberia enviar para el metodo

Inicialmente debe tener estos campos principales 
![image](https://user-images.githubusercontent.com/19983790/104969819-2764d300-59af-11eb-9f32-88634bbec802.png)
 luego en cada campo principal debe tener dos datos llamados "Dato" y "InfoComplmentaria" , en "Dato" quedara la informacion que tendra el infoComplementaria, es decir, que si el infoComplementaria es ProgramaAcademico el dato seria el valor del programa academico "Ej: Ingenieria de sistemas" 
![image](https://user-images.githubusercontent.com/19983790/104970078-eae5a700-59af-11eb-9170-3ad5e5662899.png)

y la misma escructura para los demas campos principales a excepcion de TercerosId dicho campo es la informacion del tercero que agrega informacion a la tabla, se puede saber que tercero es haciendo una peticion tipo get a la api o desde el usuario que se este utilizando y quedaria de esta forma:

![image](https://user-images.githubusercontent.com/19983790/104969965-8aef0080-59af-11eb-9702-7cebac706afa.png)
**Todo esto para que al final el json quede de la siguiente forma:**
![image](https://user-images.githubusercontent.com/19983790/104970026-c8ec2480-59af-11eb-88e7-92e90fba0d43.png)

**Comment by Camiloqui** [comment]
El pull request de dicho controlador y modfiicacion de tabla se encuentra en el siguiente link https://github.com/orgs/udistrital/projects/23#card-53069858

**Comment by Camiloqui** [comment]
Luego de usar el metodo creado se realizan pruebas con postman y en el local, cuando se envia la informacion desde el postman este retorna el id padre y en la base de datos queda la información registrada de la siguiente manera: 
![image](https://user-images.githubusercontent.com/19983790/104970793-46b12f80-59b2-11eb-8b4e-100bc9b51d3f.png)

**Comment by Camiloqui** [comment]
Demostrando que el primer campo insertado esta en null en el atributo "Info_complementaria_tercero_padre_id" pero los demas datos tienen registrado en ese campo el id del padre que en este caso es 20696 en la base de datos local donde se realizaron las pruebas

**Comment by EstefaniaPerezTorres** [comment]
# Mostrar información en el cliente

Para el formulario de _Cambio de categoría_ se muestran los documentos de las titulación que el usuario subió previamente al sistema y la categoría actual junto con la fecha en que se realizó el cambio. Para mostrar esa información se realizaron dos métodos en el cliente dentro de **crud-produccion_academica.component**.

## Método para titulaciones
Este método consulta la información complementaria del Tercero que pertenece al grupo 18, busca los que tienen de nombre **DOCUMENTO_ID** y **NIVEL_FORMACIÓN** de un Padre, tare el documento de NUXEO y lo asigna en el campo correspondiente del formulario.
![code](https://user-images.githubusercontent.com/72519041/106283937-8842a580-6210-11eb-83c5-c3e783f13623.png)

## Método para Categoría actual y Fecha de cambio
Este método consulta las solicitudes inactivas del usuario y las filtra por las que fueron cambios de categoría, toma el último cambio y asigna los valores a los campos correspondientes del formulario. En caso que este realizando el primer cambio de categoria el campo de Categoria estará vacío y la Fecha será la del día actual.
![code](https://user-images.githubusercontent.com/72519041/106284229-f1c2b400-6210-11eb-91a1-a797ee275267.png)

**Comment by fabianbarreto02** [comment]
se por terminada la issue
