### ISSUE TITLE
Creación de los mockups de consulta de solicitudes

### ISSUE THREAD

**Issue by mvcalderonc** [udistrital/produccion_academica_cliente#6]

**Comment by EstefaniaPerezTorres** [comment]
### Mockup para que el docente consulte sus solicitudes en proceso
En parte de la derecha es como el docente podrá ver la solicitud con los comentarios correspondientes
![Mockups producción académica-Docente solicitud en proceso](https://user-images.githubusercontent.com/72519041/97017716-e118e880-1513-11eb-8ba5-bc2993d29313.png)

**Comment by fabianbarreto02** [comment]
Se debe realizar los ajustes correspondientes anexar documentación

**Comment by CrissUD** [comment]
# Actualización de Mockup

@fabianbarreto02 
Se realiza actualización de mockup:
![Mockups producción académica-Docente solicitud en proceso (1) (1)](https://user-images.githubusercontent.com/44172561/98425989-2e916b80-2065-11eb-9f20-ec4624acb09e.png)


- Enlace para revisión de mockups:
[Documento draw.io](https://drive.google.com/file/d/1R3jhq-nkBm7w3Bd3GOgfMUneiXNFFlQR/view?usp=sharing)

**Comment by fabianbarreto02** [comment]
Se revisan los ajustes realizados a los mockups sugeridos por el usuario, se da por finalizada la issue se autoriza el mockups en la [reunión](https://drive.google.com/file/d/1WsayeR_Q3OfOGeIgaQjmss4WBxS8POsa/view) con el usuario
