### ISSUE TITLE
Terminar lógica para el modulo de evaluaciones

### ISSUE THREAD

**Issue by CrissUD** [udistrital/produccion_academica_cliente#62]

**Comment by CrissUD** [comment]
# Ajustes en mockup de visualización de evaluación

Se realizan ajustes con la visualización de las evaluaciones añadiendo información del evaluador y además el puntaje total de la evaluación para que se vea de una manera mas clara: 
![image](https://user-images.githubusercontent.com/44172561/105494811-5918bb00-5c89-11eb-9e34-f63d9fdca322.png)

![image](https://user-images.githubusercontent.com/44172561/105494837-5f0e9c00-5c89-11eb-9e73-32d20891d82d.png)

**Comment by CrissUD** [comment]
# Generación de pdf para los formularios de evaluación:

Se crea lógica para generar un archivo Pdf del formulario que el par externo diligencia una vez evalúa una producción académica, para la generación de este se utilizan dos nuevas dependencias:
![dependencias](https://user-images.githubusercontent.com/44172561/105495437-2d4a0500-5c8a-11eb-9b98-4d2ec6813d97.png)

Una vez el par académico registre su evaluación, se llamará al método **downloadAsPDF** el cual se encargará de realizar el pdf del formulario:
![pdf](https://user-images.githubusercontent.com/44172561/105495639-68e4cf00-5c8a-11eb-9fd1-a5a3c84ab744.png)

Se genera además una condición adicional con los formularios de evaluación para producción de software o innovación tecnológica ya que estos formularios son demasiado largos y se deben repartir en dos hojas del pdf,
otro detalle a mencionar es que para poder crear el canvas del formulario se debe hacer una referencia al formulario en cuestion con las etiquetas de selección de angular: 
![etiquetapdf](https://user-images.githubusercontent.com/44172561/105495902-be20e080-5c8a-11eb-9efd-ba917e2ed0e5.png)

Por cuestión de prueba se descarga el pdf para ver los resultados:
* Formulario de una sola página
![image](https://user-images.githubusercontent.com/44172561/105496651-c594b980-5c8b-11eb-9701-ab1e0441cdad.png)
![image](https://user-images.githubusercontent.com/44172561/105496682-d1807b80-5c8b-11eb-994a-f69f6c42699f.png)

* Formulario de dos Páginas
![image](https://user-images.githubusercontent.com/44172561/105496733-e0ffc480-5c8b-11eb-8327-1be350eb2d84.png)
![image](https://user-images.githubusercontent.com/44172561/105496752-e6f5a580-5c8b-11eb-82b5-9d48de14f970.png)
![image](https://user-images.githubusercontent.com/44172561/105496782-ef4de080-5c8b-11eb-9878-6b533cc37965.png)

**Comment by CrissUD** [comment]
# Subida de documento PDF a Nuxeo

Una vez el pdf es generado, se debe obtener el blob del mismo y así construir el objeto que será llevado a nuxeo (Este objeto debe insertarse en un arreglo)

![blob](https://user-images.githubusercontent.com/44172561/105496999-3fc53e00-5c8c-11eb-9cad-7ace309041cc.png)

Una vez construido el arreglo se envía al método **uploadFilesToMetadaData** que se encarga de la subida del archivo a nuxeo y obtención del enlace del mismo:

![uploadFilesToMetadaData](https://user-images.githubusercontent.com/44172561/105497189-84e97000-5c8c-11eb-9fd8-7fdcccabf720.png)

En este caso como se menciona, se sube primero el documento a nuxeo y una vez este envía la respuesta de éxito se vuelve a usar el servicio nuxeo Service para consultar el enlace y poderlo guardar en base de datos,

con estos datos una vez se actualiza el registro de la solicitud de evaluacion en el campo de referencia se adiciona el id del registro en documentos service y el link que devuelve nuxeo:
![createEvaluacion](https://user-images.githubusercontent.com/44172561/105497647-22dd3a80-5c8d-11eb-8d1d-49012446bafc.png)


Si se entra a nuxeo, es posible comprobar la subida del documento pdf generado de la evaluación:
![image](https://user-images.githubusercontent.com/44172561/105497750-4607ea00-5c8d-11eb-837a-f437e62da84c.png)

**Comment by CrissUD** [comment]
# Lógica para verificación de evaluaciones y promedio de las mismas

Una vez se esta revisando alguna solicitud en la cual ya se han realizado 2 o mas evaluaciones se habilitará una opción en donde el personal de secretaría o administración docencia podrán verificar las evaluaciones que se ha realizado o de lo contrarío podrían seguir enviando mas invitaciones de evaluaciones:
![image](https://user-images.githubusercontent.com/44172561/105498486-43f25b00-5c8e-11eb-8f21-37ba761171a1.png)

En caso de no tener dos de las solicitudes enviadas en el estado de evaluada esta opción no estará habilitada:
![image](https://user-images.githubusercontent.com/44172561/105498782-95024f00-5c8e-11eb-8300-d6d713f8211b.png)

Una vez se oprime el botón, se genera un pop up donde muestra el resultado de cada una de las evaluaciones realizadas y el promedio entre estas: 

![image](https://user-images.githubusercontent.com/44172561/105499452-7ea8c300-5c8f-11eb-910b-59e3d68cb175.png)

En este momento el personal de oficina de docencia podrá decidir si las evaluaciones realizadas son correctas y en ese caso las podrá verificar, de lo contrario este seguirá teniendo la opción de enviar una nueva invitación a algún par externo: 

Aquí es posible ver un ejemplo de 3 evaluaciones realizadas: 
![image](https://user-images.githubusercontent.com/44172561/105500155-7ac97080-5c90-11eb-940e-61e114041dd5.png)
![image](https://user-images.githubusercontent.com/44172561/105500166-7ef58e00-5c90-11eb-9602-ff43713c30f9.png)

Una vez se da en verificar, la solicitud padre de estas evaluaciones tomará el resultado promedio entre estas evaluaciones y además cambiará de estado para estar lista ante presentación de comité:

![image](https://user-images.githubusercontent.com/44172561/105500535-0511d480-5c91-11eb-8a2c-b8ac16eb17a1.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizada la idea
