### ISSUE TITLE
Pre-manual de usuario

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#71]

**Comment by EstefaniaPerezTorres** [comment]
# Pre-manual de usuario
Se realiza manual para los cuatro tipos de usuarios:
1. Docente
2. Personal administrativo de la oficina de docencia
3. Secretaria de la oficina de docencia
4. Evaluador externo

> El documento se encuentra dando clic [aquí](https://docs.google.com/document/d/1EZwKO-O3IxlfzUhN8eiqpOdrZ5nUQFJlsPdjkc8EGxY/edit?usp=sharing).

**Comment by fabianbarreto02** [comment]
Agregar documento de roles y usuarios

**Comment by EstefaniaPerezTorres** [comment]
# Roles y usuarios
El documento se encuentra en el siguiente enlace: [Documento de roles y usuarios](https://docs.google.com/document/d/1ouc-_qUJJWcR4wRbRF0DgRuaMCeE4KULsPIi3CGkNx4/edit?usp=sharing)

**Comment by fabianbarreto02** [comment]
se da por terminado la issue
