### ISSUE TITLE
Manual de APIS con variables de entorno

### ISSUE THREAD

**Issue by Camiloqui** [udistrital/produccion_academica_cliente#72]

**Comment by Camiloqui** [comment]
![image](https://user-images.githubusercontent.com/19983790/106290349-fa66ba80-620f-11eb-8caf-b9196f0138fc.png)

https://drive.google.com/file/d/1Do0Pa6zUToz1FWtXiMaxxRzLrDRBPD_5/view?usp=sharing

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
