### ISSUE TITLE
Creación de los mockups de observaciones de solicitudes

### ISSUE THREAD

**Issue by mvcalderonc** [udistrital/produccion_academica_cliente#8]

**Comment by EstefaniaPerezTorres** [comment]
### El mockup para que la secretaría de la oficina de docencia realice comentarios a las solicitudes
![Mockups producción académica-Secretaria verificar solicitudes](https://user-images.githubusercontent.com/72519041/97017358-6a7beb00-1513-11eb-875d-8f6b6fa4d01a.png)

**Comment by fabianbarreto02** [comment]
Se debe realizar la actualización del mockups y documentación

**Comment by CrissUD** [comment]
# Actualización de Mockup

@fabianbarreto02 
Se realiza actualización de mockup:
![Mockups producción académica-Secretaria verificar solicitudes](https://user-images.githubusercontent.com/44172561/98426109-9942a700-2065-11eb-87fd-bd39a7836fca.png)

- Enlace para revisión de mockups:
[Documento draw.io](https://drive.google.com/file/d/1R3jhq-nkBm7w3Bd3GOgfMUneiXNFFlQR/view?usp=sharing)

**Comment by fabianbarreto02** [comment]
Se revisan los ajustes realizados a los mockups sugeridos por el usuario, se da por finalizada la issue se autoriza el mockups en la [reunión](https://drive.google.com/file/d/1WsayeR_Q3OfOGeIgaQjmss4WBxS8POsa/view) con el usuario
