### ISSUE TITLE
Tema de interfaz cliente

### ISSUE THREAD

**Issue by EstefaniaPerezTorres** [udistrital/produccion_academica_cliente#83]

**Comment by EstefaniaPerezTorres** [comment]
# Actualización tema Interfaz gráfica
Se cambia logo, icono de ventana, nombre de ventana y colores según los [lineamientos para aplicativos de la OAS V1](https://drive.google.com/file/d/1ZgewUmMaMiZbWM8WicZcCBPF4epXe8gE/view?usp=sharing)

![image](https://user-images.githubusercontent.com/72519041/107053681-1680d380-679d-11eb-86ec-e4e25a5b78a6.png)

## Logos
Para que funcione el icono de la pestaña se debe convertir el icono a formato .ico y dejar el logo con fondo transparente en la carpeta **src**. El logo del header se encuentra en la carpeta **src/assets/images**.

![kyron_logo](https://user-images.githubusercontent.com/72519041/107054278-e7b72d00-679d-11eb-9228-9114e88bdbf6.png)


![kyron_icono](https://user-images.githubusercontent.com/72519041/107054339-fdc4ed80-679d-11eb-90fc-7040c2f776ed.png)


![kyron_logo_transparente](https://user-images.githubusercontent.com/72519041/107054303-f0a7fe80-679d-11eb-88f9-238e08c193fd.png)


> Colores
> Principal: 4486AA
> Medio: 5A95B8
> Claro: 83B6D4

**Comment by fabianbarreto02** [comment]
se da por terminado la issue
